name: Simple CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print a message
        run: |
         echo "Push event on branch ${{ github.ref }}"
         echo "Commit SHA: ${{ github.sha }}"
         echo "Pusher: ${{ github.actor }}"
         echo "Repository: ${{ github.repository }}"
       
