name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_PEM_KEY }}

      - name: Copy files to EC2 instance
        run: scp -r . ubuntu@${{ secrets.EC2_HOST }}:/var/www/html

      - name: SSH into EC2 instance and reload Nginx
        run: ssh ubuntu@${{ secrets.EC2_HOST }} 'sudo systemctl reload nginx'
